apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 100m
              memory: 160Mi
            limits:
              memory: 512Mi
