---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: pingbot
spec:
  encryptedData:
    password: AgASb7huwypNkNec70zFIpQKP9sdp8TkFxOLgj+Yt4Mx+Drag1kK+ngGtEC244dEU5BfGXBvMJZBBn2BW2UFSt3Z1lebTzpqVvgv0ylR0RRM3jFY9K5PLx17UsL1Vm/RUFnmX7qalqM+kgv7smsHI09esboEdcpQ6in+5HDkaF1w/ma42uDp5+P7m20n+9hoL3DNmRm7Jj7JQgna/5ub2hIL0OW8FejEggzTFFtyVzGdyR5CvwaSnlcc3WsS4w5EYbC419+d1y9QW4+432qhlpCC4TKPhvLHyOUYf//NRBis6sXMmCllOXRktbDOTZ/11JXRAWUhXndKuX15vNGLL6YoniikKvmlWC93WKQwTFlv7NANX20NwDT5fuWnfir6Be9jjKv2ccENQk+ep5qrKcQBf8peJbANbAT6LC4bOhnRa7imhvKx0HZ0lUGCCeWr8DDDmEGvAHi/Kf6tRLlRXxfhneFusS7Z6skxXIjhikwAhDnZSiLpfRRoyfsDHGVbY/zTasjJk+P+JK6PK+9Q+QL5k2tRskdRK8YkJUzJY00jSNeA7AfHYcaYTldZvP3o/IxP7158+DIJwlQdxtb83auwMt7JQoRkaF1qebPIO/H4uBf9GNmWn6LNs8t/KbkQCdylRYaQ4xLAPJIR6q4bMCHpwF+cKi3+UFn6qQmEaackz7o1F7YPEfVY8sKu1gldcKGw348+B/tYtpmGVHk+bhfVRGxuu6T1laIwSHRxNrxK7sljdzW/RSjEWmmsz3oI/+DQlhztD8OxFxoIacRRh7wZ
    username: AgCKHso9imh8zygwnU8G45GqfPJgcXMrGEhM9vrGVRmqdS4EXdDWYqW9TALG7mDngKa85lGaoHFNpcL6jQogpeK3oLYDYesaqojDlg5y9yMmVE2wICsz2WDmdQGfaxVT9OAvghE5s3CsKRD6mAvxXxXcR8SRpoJV65k/bkgQhzjIQa8Hn+GjRPun2/9LmxKsdBvJqAOycfgixVY1AsbXJzc7iGOfGCkW2Gui/jKoTxjArJ6Dx4YgT438HM4ClW6DIYz5ozFPGITVP2G4EB01YZDqEYfPA0/QrNAyb+YX7JVYI6x/6wpXZin0a6AXv0XjZ54Umb+IC9u0MMWZoNSNX14P/QioBMJOI/eaLDYUmtQryLIyM+aKPng6NkWMnvDsl3phL9Szd1+T/CmwF7/dzVfYnDWRS+xbAzJLOTbFEoemMwmfJmYPjai6eVrVJFDeE6fyCecGo6pUWWVjSF+gaYxWHSERW9NZzaAVG/wdeXiVUGEiCJbhu7UbOri3vsldOvSY1R8MFh9WgaWckKIKdJfBs6KcBNKVar7hi1G0a3ywIVDUPcGYmZnWVK9DS2JQLobufVkZ75LeirOky+N3ikYagovHxMZX/CuoMjOKfcIwVVYTYHeIAE7fxZt5u13WiL+6vGFbV3Z5iGKwl5MnqxWj2/aT24HUCrnwrai8RoW0Q5qYn/jNkAyyTZSaIMJk2QTyoDh6ZfI4
  template:
    metadata:
      name: postgres-secret
      namespace: pingbot
