---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: pingbot-dev
spec:
  encryptedData:
    password: AgCuYB6wlFyzoY+65Vl1a8SJQZLOdXn+/0XQBaiyQDYaOMpoZ7Bc76eBhs+RJa13lioSv/r0W4/feJEeVw2SRLV352a5bTSliW7webZLDgv3W5JmwowyPkKd4dBJo5RKhTRvJNfhLwADaUKEj9CH1q9sQKfJSdxBe5jVfrlIhWEi+Rq2O1axz4JB20yBO+pkhhKTF5z3xReohChnjr9crae0Laz4HJLI2HmzZnusNe1ZoRdwB/BOU9Ghy5QUptan50kDaY9PujwkZZtazW4kKOPUtDpWYqUDKhE5zbTnYiRxdk+2nUorSKKbdLZzYGy3VsIwpme0No4XH+1qRKRE8UdPe9X+UxXBdt5OUC4y4Kj+AUdTfFyT7t7BZh/Q9XliwrPEBKLTXKB4kswpmvTxa/E4/IwlD2igdObtAZLHSqEb+UjUynGfirx/luhrgoEwneA+SQwJGZh9ElJw4P2V7MlZQgqoAbbElSyI7R91gDNtkFWfYNvO8mEbjKqfoJbPoesiIHeQ5vy7jKifxaNqxKKKSFNS5dhkx6EGXQ0Dvbr7oEcsWou70aCAASFD2dVIHwmW20YOVS0y/+t4M5ImgJYmiAHa1vQxi2BrkaBhNw4btOkvT1PwkrvFL/vpwI7+90LStynCYYk4cZNnlIA2Hcq0JNNMshw46LpbArj4Ix65rgUv7fPUdWpwS0W7MoCxrfn4Duz68YKt+iIN5k5uAzeeQoVWEf4SGSDvxvtJDIOY/VltWJ57D62/dqv1Z3OOGvjLqCBEZ8XeqU1a2AH9apR9
    username: AgB8LZq2DCyvGCeY3wG/ctP5NQsmecs4TPa4wALbXIjWfewYDrbo6vz12tKgH+chy3GnlLrSiiidPN4AC++vjZEKQT92SVXrKyN6YmEffBVbArA4HcYDDsBq8t7ZfpAGDEBrV+jCUz16rQc1r7Cwc9GMbaentl6kSSr1maJpWOjuh1hDBhMFveJ81TdVzqUNG0PfcmN6k13H52+5rzTiVt8Y5eCR4NtKrUP/BqYCRBFiXpn6qNmjwGSrj0YbngCLeP5w1C+dTiMx8Pccvf2U8qNH6UyBnJF+a9h/20+rUuZGHu0BWXo2U+OX62STdfzeDFlm3Dh75yPoqSeZcJi+OF39VMPC3iYbMNzSNoiOplRyHpU6k+YcQs3BwuRDVd6lu14FW6d3adKRCduo8mK5bU7HuOp26AHkP4ybnpw+lfzQm89eupy0mCk6P6RFceKpq5/m7p6+ytL4P57HCJ35so1bo9nXVSIy+QO2hli6+1Y2kRryZRe3VYXQEZaijN4N3OE90yDCvSY7Vg4H6Moc4IONhWZUwptYvkUkGxqNngYukgLS8CaaZj80M855IjzreN+mMAFW5CxMp80soZq0R89L3v68riKQkfab2gtxz39Cnx3qvn/F7tyWJjIgMsU7vlm+vJSDScJNOtlMbJt3KZ6ZgfSVJdiLl2AegLB6w0l8b/Z1J7qlu7cH/Iwt38o6SzmBpy5GFuPF
  template:
    metadata:
      name: postgres-secret
      namespace: pingbot-dev
