# This workflow builds, pushes build to dev-dist branch, and deploys to development
name: Cleanup deployments

on:
  workflow_dispatch:

jobs:
  cleanup-dev:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Development
          onlyRemoveDeployments: true

  cleanup-prod:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: Production
          onlyRemoveDeployments: true
