# This workflow builds and pushes build to dev-dist branch
name: Lint, Build, and Publish

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use current Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: |
          npm i -g npm@latest
          npm ci
        
      - name: Lint
        run: npm run lint

  build:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    # Only trigger for my PRs, other PRs will simply just run lint
    if: ${{ github.event.pull_request.author_association == 'OWNER' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use current Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: |
          npm i -g npm@latest
          npm ci

      # We essentially move all required files to a hidden, untracked folder called .out
      # npm run deploy automatically builds and registers slash commands
      - name: Build & Deploy
        env:
          TOKEN: ${{ secrets.DEV_TOKEN }}
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
        run: |
          npm run deploy
          mkdir .out
          cp -r * .out
          mv .env-cmdrc .out

      # Then after we checkout the branch, we can overwrite all files with the ones in .out
      # We also include the commit message to be the same as original commit
      - name: Checkout and push to dev-dist
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin dev-dist
          rm -rf dist
          git checkout dev-dist
          rm -r *
          mv .out/* .
          mv .out/.env-cmdrc .
          rmdir .out
          git add .
          git commit -m "${{ github.event.pull_request.head.label }}" || true
          git push origin dev-dist

  publish:
    needs: [lint, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Use current Node.js
        uses: actions/setup-node@v3
        with:
          node-version: current

      - name: Install dependencies
        run: |
          npm i -g npm@latest pm2
          npm i dotenv

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'none' # Required by the action
      
      - name: Add to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Omitting output for security
      - name: Deploy to development
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEV_DEPLOY_PATH: ${{ secrets.DEV_DEPLOY_PATH }}
        run: pm2 deploy development > /dev/null
